name: build and publish to s3 on push to main

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
          cache-dependency-path: subdir/go.sum

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: |
          go get .

      - name: Build
        run: GOOS=linux GOARCH=arm GOARM=6 go build -v

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::524383445033:role/s3-lmnl-publisher-role
          role-session-name: github-actions-role-ds
          aws-region: us-east-1
      - name: aws deploy
        run: aws s3 copy ./bestia s3://lmnl.mx/bestia/bestia
