name: build and publish to s3 on push to main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24.6"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: subdir/go.sum
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: GOOS=linux GOARCH=arm GOARM=6 go build -v

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::524383445033:role/s3-lmnl-publisher-role
          role-session-name: github-actions-role-ds
          aws-region: us-east-1
      - name: aws deploy
        run: aws s3 copy ./bestia s3://lmnl.mx/bestia/bestia
